package com.islamic.bangla.presentation.theme

import androidx.compose.ui.graphics.Color

// ---------------------------------------------------------------------------
// Light theme — calm paper background, deep emerald primary, muted bronze
// secondary (restrained: no loud gold), soft teal tertiary for prayer accents.
// ---------------------------------------------------------------------------
val LightPrimary = Color(0xFF0B6B3A)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFB7EDC6)
val LightOnPrimaryContainer = Color(0xFF062E1A)
val LightSecondary = Color(0xFF6E6046)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFEFE6D2)
val LightOnSecondaryContainer = Color(0xFF2E2814)
val LightTertiary = Color(0xFF3E7A6C)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFCDE8DF)
val LightOnTertiaryContainer = Color(0xFF072A24)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF7FAF6)
val LightOnBackground = Color(0xFF161D18)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF161D18)
val LightSurfaceVariant = Color(0xFFE8F0E9)
val LightOnSurfaceVariant = Color(0xFF414942)
val LightSurfaceLowest = Color(0xFFFFFFFF)
val LightSurfaceLow = Color(0xFFF3F6F2)
val LightSurfaceContainer = Color(0xFFECF1EB)
val LightSurfaceHigh = Color(0xFFE6ECE5)
val LightSurfaceHighest = Color(0xFFE0E7DF)
val LightOutline = Color(0xFF717971)
val LightOutlineVariant = Color(0xFFC1C9C0)
val LightInverseSurface = Color(0xFF2F3230)
val LightInverseOnSurface = Color(0xFFEFF2EE)
val LightInversePrimary = Color(0xFF83D99E)

// ---------------------------------------------------------------------------
// Dark theme — designed for nighttime reading, NOT an inverted light theme:
// deep ink surfaces with a faint green cast, softened accents, warm sand
// secondary, comfortable (never pure-white) text.
// ---------------------------------------------------------------------------
val DarkPrimary = Color(0xFF7BD79A)
val DarkOnPrimary = Color(0xFF00331A)
val DarkPrimaryContainer = Color(0xFF0B5A32)
val DarkOnPrimaryContainer = Color(0xFFD3F5DE)
val DarkSecondary = Color(0xFFD3C49A)
val DarkOnSecondary = Color(0xFF3A2F15)
val DarkSecondaryContainer = Color(0xFF4A3F28)
val DarkOnSecondaryContainer = Color(0xFFF2E8CF)
val DarkTertiary = Color(0xFF8ED0BF)
val DarkOnTertiary = Color(0xFF00382D)
val DarkTertiaryContainer = Color(0xFF1E4A40)
val DarkOnTertiaryContainer = Color(0xFFC4ECE0)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF0C120E)
val DarkOnBackground = Color(0xFFE2E8E3)
val DarkSurface = Color(0xFF121815)
val DarkOnSurface = Color(0xFFE2E8E3)
val DarkSurfaceVariant = Color(0xFF1D2620)
val DarkOnSurfaceVariant = Color(0xFFBCC8BE)
val DarkSurfaceLowest = Color(0xFF090D0B)
val DarkSurfaceLow = Color(0xFF0C120E)
val DarkSurfaceContainer = Color(0xFF121815)
val DarkSurfaceHigh = Color(0xFF1C2420)
val DarkSurfaceHighest = Color(0xFF272F29)
val DarkOutline = Color(0xFF8A938B)
val DarkOutlineVariant = Color(0xFF2E3831)
val DarkInverseSurface = Color(0xFFE2E8E3)
val DarkInverseOnSurface = Color(0xFF121815)
val DarkInversePrimary = Color(0xFF0B6B3A)
